# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publicar nexus

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag'
        default: 'develop'
        required: true

jobs:
  nexus-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: sonatype-nexus
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.OSS_GPG_PRIVATE_KEY }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish on nexus
        run: mvn -B deploy -Dmaven.test.skip=true -Dfindbugs.skip=true -DperformRelease=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEYNAME: ${{ secrets.OSS_GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.OSS_GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
